### ISSUE TITLE
Talos

### ISSUE THREAD

**Issue by OhMyMndy** [OhMyMndy/homelab#3]
Talos cluster in Docker with Nginx Ingress controller:

```bash
talosctl cluster create  --talos-version 1.8.4 \
--kubernetes-version 1.31.2 \
--registry-mirror registry.k8s.io=https://registry-k8s-io.home.ohmymndy.com \
--registry-mirror docker.io=https://registry-docker-io.home.ohmymndy.com \
--registry-mirror gcr.io=https://registry-gcr-io.home.ohmymndy.com \
--registry-mirror ghcr.io=https://registry-ghcr-io.home.ohmymndy.com

kubectl create ns ingress-nginx
kubectl label ns ingress-nginx pod-security.kubernetes.io/enforce=privileged

helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
--namespace ingress-nginx \
--set controller.kind=DaemonSet \
--set controller.hostPort.enabled=true \
--set controller.service.type=ClusterIP \
--set controller.hostNetwork=true
```

Install OpenBao:
```bash
helm upgrade --install openbao openbao/openbao --create-namespace \
--namespace openbao --version 0.4.0 \
--set server.ingress.enabled=true --set server.ingress.ingressClassName=nginx \
--set 'server.ingress.hosts[0].host=openbao.10.5.0.3.sslip.io' \ 
--set server.dataStorage.size=1Gi

```

Nginx manifest to test Ingress:
```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
      - containerPort: 80
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nginx.10.5.0.3.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
```
